### ISSUE TITLE
Expand "keytar not installed" error text 

### ISSUE THREAD

**Issue by JTonda** [zowe/imperative#40] opened 2018-10-09 21:16 UTC
_From @dogboydog on June 29, 2018 14:41_

It would be nice if we could explain what could have went wrong that led to keytar not being installed. For instance, adding a note that it means native dependencies didn't install correctly (maybe due to native build tools not being installed) and give the user some steps to diagnose the cause.

_Copied from original issue: gizafoundation/imperative#120_

**Comment by JTonda** [comment] 2018-10-09 21:16
_From @PeteSwauger on June 29, 2018 17:1_

I received this error due to the 'build' subfolder not being present.  The 'keytar' folder was there and 'src' and 'lib' subfolders.  I had to install keytar in order to have the 'build' folder installed.  This happened a many times but no pattern was recognized.

**Comment by JTonda** [comment] 2018-10-09 21:16
_From @dogboydog on June 29, 2018 17:4_

It also happens when users don't have the build tools installed or encounter a permissions or other error while building the native keytar code which is probably the most common cause

**Comment by JTonda** [comment] 2018-10-09 21:16
_From @AHumanFromCA on July 2, 2018 13:59_

I'd also like to point out that most of the time keytar doesn't get installed it is actually node report that fails the install first. This then causes the keytar install to be skipped (though if node report fails so does keytar).

This could be one way that @PeteSwauger experiences his symptoms.

**Comment by tucker01** [comment] 2018-10-11 12:35
Plenty of folks have encountered this issues and under some circumstances (such as upgrading versions of Node.js) there are additional relevant details that should be surfaced.

**Comment by AHumanFromCA** [comment] 2018-10-11 14:45
Duplicate of #27.

This issue was opened in the zowe/imperative repository before the corresponding issue was copied over from the other repo. With that being said, we should close one of these issues and track the other.

FYI: #27 has some links to code that could be modified to address the problem. So I propose closing this one and keeping the other.

**Comment by AHumanFromCA** [comment] 2018-10-11 14:50
Closing this in favor of #27

**Closed by AHumanFromCA** 2018-10-11 14:50 UTC
Labels: enhancement, profiles
